import React, { useState, useEffect } from 'react';
import ItemsCarousel from 'react-items-carousel';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {motion}  from "framer-motion"
import Button from 'react-bootstrap/Button'
import ScrollDown from '../components/ScrollDown'



const container = {
  hidden: { opacity: 1, scale: 0 },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delayChildren: 0.3,
      staggerChildren: 0.2,
      delay: 1
    }
  },
};


export default function Home() {
  const [activeItemIndex, setActiveItemIndex] = useState(0);
  useEffect(()=> {
    const heightOutput = document.querySelector('#height')
    console.log(heightOutput)

  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet"></link>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" 
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"/>

      </Head>
      <div className={styles.toppage}>
        <div className={styles.herobg}>
          {/* <Image src='/mainBgImg.jpg' layout="fill" objectFit="cover" className={styles.img}/> */}
        </div>
        <div className={styles.topmaincontent}>
          <div className={styles.landingcatcher}>
            <div className={styles.landingtext}>
              <div className={styles.textcontainer}>
                <motion.div animate="visible" initial="hidden" transition={{}} variants={container} >
                  <div>
                    <span className={styles.bigwords1}>
                      <span>CONNECT </span> <br />
                      <span style={{width:'100%'}}>WITH YOUR </span>
                    </span>
                  </div>
                </motion.div>                
                <div className={styles.topbottomtext}>
                  <div className={styles.bigwords2}>
                    SPORTS <br /> HEROES
                  </div>
                  <div className={styles.smalltext}>
                    Connect with the gratest sportspeople of all time through NFTs.
                    For the first time in history, you can own part of your Icon's story
                    forever, or trade it.
                  </div>
                </div>

              </div>
              
            </div>
          </div>
          <div>
          </div>
          
          <ScrollDown />
        </div>
      </div>
      <div style={{height: '100%'}} className={styles.featuredAthletes}>
        <div className={styles.featuredTextContainer}>
          <div className={styles.featuredText}>An ever-growing list of athletes to collect and inspire</div>
        </div>
        <div className={styles.carouselContainer}>
          <div  className={styles.featuredcarousel} >
            <ItemsCarousel
              infiniteLoop={false}
              gutter={12}
              activePosition={'center'}
              chevronWidth={60}
              disableSwipe={false}
              alwaysShowChevrons={false}
              numberOfCards={1}
              slidesToScroll={1}
              outsideChevron={false}
              showSlither={true}
              firstAndLastGutter={true}
              activeItemIndex={activeItemIndex}
              requestToChangeActive={value => setActiveItemIndex(value)}
              rightChevron={<Button>{'>'}</Button>}
              leftChevron={<Button>{'<'}</Button>}
            >
              <div className={styles.carouselItem} style={{background: 'url(/stadium.jpg)'}}>First card</div>
              <div className={styles.carouselItem} style={{background: 'url(/stadium.jpg)' }}>Second card</div>
              <div className={styles.carouselItem} style={{background: 'url(/stadium.jpg)' }}>Third card</div>
              <div className={styles.carouselItem} style={{background: 'url(/stadium.jpg)' }}>Fourth card</div>
          </ItemsCarousel>
          </div>
        </div>
      </div>

    </div>
  )
}
